/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AboutDialog: typeof import('./src/components/dialogs/AboutDialog.vue')['default']
    AddPrintersDialog: typeof import('./src/components/features/add_printers/AddPrintersDialog.vue')['default']
    AppearanceSettings: typeof import('./src/components/settings/AppearanceSettings.vue')['default']
    Avatar: typeof import('primevue/avatar')['default']
    BuildingPanel: typeof import('./src/components/features/building/BuildingPanel.vue')['default']
    Button: typeof import('primevue/button')['default']
    Checkbox: typeof import('primevue/checkbox')['default']
    ClippingPlane: typeof import('./src/components/features/model_control/ClippingPlane.vue')['default']
    CollisionFloatingPanel: typeof import('./src/components/features/collision/CollisionFloatingPanel.vue')['default']
    CollisionPanel: typeof import('./src/components/features/collision/CollisionPanel.vue')['default']
    Dialog: typeof import('primevue/dialog')['default']
    DynamicDialog: typeof import('primevue/dynamicdialog')['default']
    EditorPanel: typeof import('./src/components/UI/EditorPanel.vue')['default']
    InputNumber: typeof import('primevue/inputnumber')['default']
    InputText: typeof import('primevue/inputtext')['default']
    LeftPanel: typeof import('./src/components/layout/LeftPanel.vue')['default']
    MachineSelection: typeof import('./src/components/features/add_printers/MachineSelection.vue')['default']
    Menu: typeof import('primevue/menu')['default']
    ModelEditor: typeof import('./src/components/features/model_control/ModelEditor.vue')['default']
    ModelEditorFieldRow: typeof import('./src/components/features/model_control/ModelEditorFieldRow.vue')['default']
    ModelList: typeof import('./src/components/features/model_info/ModelList.vue')['default']
    ModelParamsPanel: typeof import('./src/components/features/model_info/ModelParamsPanel.vue')['default']
    ModelToolbar: typeof import('./src/components/features/model_control/ModelToolbar.vue')['default']
    OrthoModeDialog: typeof import('./src/components/dialogs/OrthoModeDialog.vue')['default']
    Password: typeof import('primevue/password')['default']
    Popover: typeof import('primevue/popover')['default']
    ProgressSpinner: typeof import('primevue/progressspinner')['default']
    ResinAutoChangeDialog: typeof import('./src/components/dialogs/ResinAutoChangeDialog.vue')['default']
    RightPanel: typeof import('./src/components/layout/RightPanel.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SafetyGapPanel: typeof import('./src/components/features/collision/SafetyGapPanel.vue')['default']
    ScatterPanel: typeof import('./src/components/features/objects/ScatterPanel.vue')['default']
    Select: typeof import('primevue/select')['default']
    SelectLocale: typeof import('./src/components/features/basic_settings/SelectLocale.vue')['default']
    SettingsDialog: typeof import('./src/components/settings/SettingsDialog.vue')['default']
    Slider: typeof import('primevue/slider')['default']
    SteppedInput: typeof import('./src/components/UI/SteppedInput.vue')['default']
    Tab: typeof import('primevue/tab')['default']
    TabList: typeof import('primevue/tablist')['default']
    TabPanel: typeof import('primevue/tabpanel')['default']
    TabPanels: typeof import('primevue/tabpanels')['default']
    Tabs: typeof import('primevue/tabs')['default']
    Toast: typeof import('primevue/toast')['default']
    ToggleSwitch: typeof import('primevue/toggleswitch')['default']
    ToolbarButton: typeof import('./src/components/UI/ToolbarButton.vue')['default']
    ToothLoadingDialog: typeof import('./src/components/UI/ToothLoadingDialog.vue')['default']
    Tree: typeof import('primevue/tree')['default']
    UdpServerDialog: typeof import('./src/components/features/add_printers/UdpServerDialog.vue')['default']
    UploadBtn: typeof import('./src/components/features/file_loading/UploadBtn.vue')['default']
    UserSidebarShell: typeof import('./src/components/layout/UserSidebarShell.vue')['default']
    VDivider: typeof import('./src/components/UI/VDivider.vue')['default']
    VirtualScroller: typeof import('primevue/virtualscroller')['default']
  }
  export interface ComponentCustomProperties {
    Ripple: typeof import('primevue/ripple')['default']
    Tooltip: typeof import('primevue/tooltip')['default']
  }
}
